// Phase 0 parity harness: FastAPI (via fixtures generated by
// tests/gen_fastapi_fixtures.py into tests/expected/) vs sql.js running the
// same ported query layer (browser/js/query/*.js) against the SAME bytes of
// data/explorer.db.
//
// Expected JSON comes from the Python fixture generator, driven by the shared
// tests/fixtures.manifest.json — not from TestClient inside this process.
//
// Comparison rule (section 5a.B3): exact everywhere EXCEPT the
// canonically-compared keys, which are normalized (sorted) before diff:
//   - /api/search  result arrays: keys `documents`, `provisions`,
//     `annotators`, `units`
//   - /api/units   each row's `support` array
// These are UNORDERED because the two SQLite engines (Python 3.53.x vs
// sql.js ~3.45.1) may emit joined/aggregated rows in different orders; every
// other collection is deterministically ordered and compared byte-for-byte
// (structurally). Tied `ORDER BY ... DESC` collections (label_distribution,
// /api/labels, /api/fragment-types) have no ties in the current data; if a
// rebuild ever introduces one they must move into the canonical set.
//
// The plan mandates diffing raw JSON bytes; JS always escapes U+2028/U+2029
// while Python's ensure_ascii=False does not. This harness therefore parses
// both sides and compares the JSON VALUE trees (byte-equivalent for ASCII/
// BMP content), so that documented edge cannot trip the suite.
//
// Node floor: `node --test` ESM inference needs Node >= ~20.19/22 (env: 26.5).
//
// Unlike tests/frontend/*.test.js, this file is NOT globbed by tests.sh — it
// is invoked explicitly (section 5a.D16).

import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import initSqlJs from "../frontend/sqljs/vendor/sql.js/sql-wasm.js";
import { createQuery } from "../frontend/sqljs/js/query/sqlite-bridge.js";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.dirname(HERE);
const DB_PATH = path.join(ROOT, "data", "explorer.db");
const EXPECTED_DIR = path.join(HERE, "expected");
const MANIFEST_PATH = path.join(HERE, "fixtures.manifest.json");
const SQLJS_DIR = path.join(ROOT, "frontend", "sqljs", "vendor", "sql.js");

// ---- canonical comparison --------------------------------------------------

const CANONICAL_PATH_PATTERNS = [
  ["documents"],
  ["provisions"],
  ["annotators"],
  ["units"],
  ["rows", "*", "support"],
];

function isCanonicalArrayPath(p) {
  return CANONICAL_PATH_PATTERNS.some(
    (pat) => pat.length === p.length && pat.every((node, i) => node === "*" || node === p[i])
  );
}

// Deep copy with object keys sorted (stable canonical element serialization).
function canonicalCopy(v) {
  if (v === null || typeof v !== "object") return v;
  if (Array.isArray(v)) return v.map(canonicalCopy);
  const out = {};
  for (const k of Object.keys(v).sort()) out[k] = canonicalCopy(v[k]);
  return out;
}

// Deep copy; canonical arrays become sorted arrays of canonicalized elements.
function normalizeForCompare(v, p = []) {
  if (Array.isArray(v)) {
    if (isCanonicalArrayPath(p)) {
      const items = v.map(canonicalCopy);
      items.sort((a, b) => {
        const sa = JSON.stringify(a);
        const sb = JSON.stringify(b);
        return sa < sb ? -1 : sa > sb ? 1 : 0;
      });
      return items;
    }
    return v.map((el, i) => normalizeForCompare(el, [...p, "*"]));
  }
  if (v !== null && typeof v === "object") {
    const out = {};
    for (const k of Object.keys(v)) out[k] = normalizeForCompare(v[k], [...p, k]);
    return out;
  }
  return v;
}

function firstDiff(a, b) {
  const n = Math.min(a.length, b.length);
  for (let i = 0; i < n; i++) if (a[i] !== b[i]) return i;
  return a.length === b.length ? -1 : n;
}

function buildFailureMessage(entry, jsSerialized, normalizedExpectedJson, normalizedActualJson) {
  const i = firstDiff(normalizedExpectedJson, normalizedActualJson);
  const window = 100;
  const show = (s) => {
    const lo = Math.max(0, i - window);
    const hi = Math.min(s.length, i + window);
    return s.slice(lo, hi);
  };
  return [
    `parity mismatch: ${entry.id} (${entry.file}, method ${entry.call.method})`,
    `first diff at byte ${i}`,
    `expected≈ ${show(normalizedExpectedJson)}`,
    `actual≈   ${show(normalizedActualJson)}`,
    `js JSON.stringify(${entry.call.method}) length = ${jsSerialized.length}`,
  ].join("\n");
}

// ---- harness state ---------------------------------------------------------

let ctxPromise = null;

function getContext() {
  if (ctxPromise) return ctxPromise;
  ctxPromise = (async () => {
    const SQL = await initSqlJs({ locateFile: (file) => path.join(SQLJS_DIR, file) });
    const bytes = fs.readFileSync(DB_PATH);
    const db = new SQL.Database(new Uint8Array(bytes));
    const q = createQuery(db);
    const seeds = {
      // Derived from FIRST-ROW queries, never hardcoded (the DB may change).
      DOC_ID: q.documents({ limit: "1" }).rows[0].doc_id,
      UNIT_ID: q.units({ limit: "1" }).rows[0].unit_id,
      ANNOTATION_ID: q.annotations({ limit: "1", offset: "0" }).rows[0].annotation_id,
    };
    return { q, seeds };
  })();
  return ctxPromise;
}

function resolveTokens(text, seeds) {
  return text.replace(/\{(DOC_ID|UNIT_ID|ANNOTATION_ID)\}/g, (match, name) => seeds[name]);
}

// ---- tests -----------------------------------------------------------------

const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));

if (!fs.existsSync(DB_PATH)) {
  console.error(`Skipping sql.js parity suite: ${DB_PATH} not found (snapshot build is a hard dependency).`);
} else {
  for (const entry of manifest.entries) {
    test(`parity: ${entry.id}`, async () => {
      const { q, seeds } = await getContext();
      const pathArgs = (entry.call.pathArgs || []).map((a) => resolveTokens(a, seeds));
      const params = {};
      for (const [k, v] of Object.entries(entry.params || {})) params[k] = resolveTokens(v, seeds);

      const result = pathArgs.length ? q[entry.call.method](...pathArgs) : q[entry.call.method](params);

      // Plan-mandated serialization (the thing the html/Node sides both emit).
      const jsSerialized = JSON.stringify(result);
      const expectedText = fs.readFileSync(path.join(EXPECTED_DIR, entry.file), "utf8");
      const expectedObj = JSON.parse(expectedText);

      const ne = JSON.stringify(normalizeForCompare(expectedObj, []));
      const na = JSON.stringify(normalizeForCompare(result, []));
      assert.equal(na, ne, buildFailureMessage(entry, jsSerialized, ne, na));
    });
  }

  test("parity: sql.js engine loads the shared DB", async () => {
    const { q } = await getContext();
    const stats = q.stats({});
    assert.equal(typeof stats.documents, "number");
    assert.equal(typeof stats.units, "number");
    assert.ok(stats.documents > 0 && stats.units > 0);
  });
}